demo1/demo1/ViewComponents/CatergoryListViewComponent.cs
using demo1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace demo1.ViewComponents
{
    public class CatergoryListViewComponent : ViewComponent
    {
        private readonly webContext _context;

        public CatergoryListViewComponent(webContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Category> catList = await _context.Categories.ToListAsync();
            return View(catList);
        }
    }
}

demo1/demo1/Views/Shared/_CartPartial.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@inject IHttpContextAccessor HttpContextAccessor


@{
    var session = HttpContextAccessor.HttpContext.Session;
    string jsoncart = session.GetString(demo1.Controllers.ProductController.CARTKEY);
    if (jsoncart != null)
    {
        var cart = JsonConvert.DeserializeObject<List<OderDetail>>(jsoncart);
        <div class="nav-item"><a asp-route="cart">Giỏ hàng(@cart.Count)</a></div>
    }
}

demo1/demo1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Bootstrap E-Commerce Template- DIGI Shop mini</title>
    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.css" rel="stylesheet">
    <!-- Fontawesome core CSS -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <!--GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <!--Slide Show Css -->
    <link href="~/css/main-style.css" rel="stylesheet" />
    <!-- custom CSS here -->
    <link href="~/css/style.css" rel="stylesheet" />

    <link href="~/css/custom.css" rel="stylesheet" />

</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/home/Index"><strong>DIGI</strong> Shop</a>
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Track Order</a></li>
                    <partial name="_LoginPartial" />

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">24x7 Support <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><strong>Call: </strong>+09-456-567-890</a></li>
                            <li><a href="#"><strong>Mail: </strong>info@yourdomain.com</a></li>
                            <li class="divider"></li>
                            <li>
                                <a href="#">
                                    <strong>Address: </strong>
                                    <div>
                                        234, New york Street,<br />
                                        Just Location, USA
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" placeholder="Enter Keyword Here ..." class="form-control">
                    </div>
                    &nbsp;
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div>
                    <a href="#" class="list-group-item active">
                        Phone
                    </a>

                    <vc:catergory-list></vc:catergory-list>

                </div>
                <div>

                </div>
                <!-- /.div -->
                <div>
                
                </div>
                <!-- /.div -->
                <div>
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-success"><a href="#">New Offer's Coming </a></li>
                        <li class="list-group-item list-group-item-info"><a href="#">New Products Added</a></li>
                        <li class="list-group-item list-group-item-warning"><a href="#">Ending Soon Offers</a></li>
                        <li class="list-group-item list-group-item-danger"><a href="#">Just Ended Offers</a></li>
                    </ul>
                </div>
                <!-- /.div -->
                <div class="well well-lg offer-box offer-colors">


                    <span class="glyphicon glyphicon-star-empty"></span>25 % off  , GRAB IT

                    <br />
                    <br />
                    <div class="progress progress-striped">
                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"
                             style="width: 70%">
                            <span class="sr-only">70% Complete (success)</span>
                            2hr 35 mins left
                        </div>
                    </div>
                    <a href="#">click here to know more </a>
                </div>
                <!-- /.div -->
            </div>
            <div class="col-md-9">
                <div>
                    <ol class="breadcrumb">
                        <li><a href="#">Home</a></li>
                        <li class="active">Phone</li>
                    </ol>
                </div>


                <main role="main" class="pb-3">
                    @RenderBody()
                </main>


            </div>
        </div>
    </div>

    <div class="col-md-12 footer-box">


        <div class="row small-box ">
            <strong>Phones :</strong> <a href="/product/list/1">Iphone</a> |  <a href="/product/list/2">samsung</a> | <a href="/product/list/3">Realme</a> |
            <a href="/product/list/4">Oppo</a> |  <a href="/product/list/5">Asus</a> | <a href="/product/list/6">Nokia</a> |<a href="/product/list/7">Vsmart</a> |
            <a href="/product/list/8">OnePlus</a> |  <a href="/product/list/1">Iphone</a> |  <a href="/product/list/2">samsung</a> | <a href="/product/list/3">Realme</a> |
            <a href="/product/list/4">Oppo</a> |  <a href="/product/list/5">Asus</a> | <a href="/product/list/6">Nokia</a> |<a href="/product/list/7">Vsmart</a> |
            <a href="/product/list/8">OnePlus</a> |  <a href="/product/list/1">Iphone</a> |  <a href="/product/list/2">samsung</a> | <a href="/product/list/3">Realme</a> |
            <a href="/product/list/4">Oppo</a> |  <a href="/product/list/5">Asus</a> | <a href="/product/list/6">Nokia</a> |<a href="/product/list/7">Vsmart</a> | view all items

        </div>
        <div class="row small-box ">
            <strong>Phones :</strong> <a href="/product/list/1">Iphone</a> |  <a href="/product/list/2">samsung</a> | <a href="/product/list/3">Realme</a> |
            <a href="/product/list/4">Oppo</a> |  <a href="/product/list/5">Asus</a> | <a href="/product/list/6">Nokia</a> |<a href="/product/list/7">Vsmart</a> |
            <a href="/product/list/8">OnePlus</a> |  <a href="/product/list/1">Iphone</a> |  <a href="/product/list/2">samsung</a> | <a href="/product/list/3">Realme</a> |
            <a href="/product/list/4">Oppo</a> |  <a href="/product/list/5">Asus</a> | <a href="/product/list/6">Nokia</a> |<a href="/product/list/7">Vsmart</a> |
            <a href="/product/list/8">OnePlus</a> |  <a href="/product/list/1">Iphone</a> |  <a href="/product/list/2">samsung</a> | <a href="/product/list/3">Realme</a> |
            <a href="/product/list/4">Oppo</a> |  <a href="/product/list/5">Asus</a> | <a href="/product/list/6">Nokia</a> |<a href="/product/list/7">Vsmart</a> | view all items
        </div>
        <div class="row small-box ">
            <strong>Phones :</strong> <a href="/product/list/1">Iphone</a> |  <a href="/product/list/2">samsung</a> | <a href="/product/list/3">Realme</a> |
            <a href="/product/list/4">Oppo</a> |  <a href="/product/list/5">Asus</a> | <a href="/product/list/6">Nokia</a> |<a href="/product/list/7">Vsmart</a> |
            <a href="/product/list/8">OnePlus</a> |  <a href="/product/list/1">Iphone</a> |  <a href="/product/list/2">samsung</a> | <a href="/product/list/3">Realme</a> |
            <a href="/product/list/4">Oppo</a> |  <a href="/product/list/5">Asus</a> | <a href="/product/list/6">Nokia</a> |<a href="/product/list/7">Vsmart</a> |
            <a href="/product/list/8">OnePlus</a> |  <a href="/product/list/1">Iphone</a> |  <a href="/product/list/2">samsung</a> | <a href="/product/list/3">Realme</a> |
            <a href="/product/list/4">Oppo</a> |  <a href="/product/list/5">Asus</a> | <a href="/product/list/6">Nokia</a> |<a href="/product/list/7">Vsmart</a> | view all items

        </div>
        <div class="row small-box pad-botom ">
            <strong>Phones :</strong> <a href="/product/list/1">Iphone</a> |  <a href="/product/list/2">samsung</a> | <a href="/product/list/3">Realme</a> |
            <a href="/product/list/4">Oppo</a> |  <a href="/product/list/5">Asus</a> | <a href="/product/list/6">Nokia</a> |<a href="/product/list/7">Vsmart</a> |
            <a href="/product/list/8">OnePlus</a> |  <a href="/product/list/1">Iphone</a> |  <a href="/product/list/2">samsung</a> | <a href="/product/list/3">Realme</a> |
            <a href="/product/list/4">Oppo</a> |  <a href="/product/list/5">Asus</a> | <a href="/product/list/6">Nokia</a> |<a href="/product/list/7">Vsmart</a> |
            <a href="/product/list/8">OnePlus</a> |  <a href="/product/list/1">Iphone</a> |  <a href="/product/list/2">samsung</a> | <a href="/product/list/3">Realme</a> |
            <a href="/product/list/4">Oppo</a> |  <a href="/product/list/5">Asus</a> | <a href="/product/list/6">Nokia</a> |<a href="/product/list/7">Vsmart</a> | view all items

        </div>
        <div class="row">
            <div class="col-md-4">
                <strong>Send a Quick Query </strong>
                <hr>
                <form>
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="form-group">
                                <input type="text" class="form-control" required="required" placeholder="Name">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="form-group">
                                <input type="text" class="form-control" required="required" placeholder="Email address">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="form-group">
                                <textarea name="message" id="message" required="required" class="form-control" rows="3" placeholder="Message"></textarea>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Submit Request</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-md-4">
                <strong>Our Location</strong>
                <hr>
                <p>
                    234, New york Street,<br />
                    Just Location, USA<br />
                    Call: +09-456-567-890<br>
                    Email: info@yourdomain.com<br>
                </p>

                2014 www.yourdomain.com | All Right Reserved
            </div>
            <div class="col-md-4 social-box">
                <strong>We are Social </strong>
                <hr>
                <a href="#"><i class="fa fa-facebook-square fa-3x "></i></a>
                <a href="#"><i class="fa fa-twitter-square fa-3x "></i></a>
                <a href="#"><i class="fa fa-google-plus-square fa-3x c"></i></a>
                <a href="#"><i class="fa fa-linkedin-square fa-3x "></i></a>
                <a href="#"><i class="fa fa-pinterest-square fa-3x "></i></a>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec nisl odio. Mauris vehicula at nunc id posuere. Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                </p>
            </div>
        </div>
        <hr>
    </div>
    <!-- /.col -->
    <div class="col-md-12 end-box ">
        &copy; 2014 | &nbsp; All Rights Reserved | &nbsp; www.yourdomain.com | &nbsp; 24x7 support | &nbsp; Email us: info@yourdomain.com
    </div>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/js/jquery-1.10.2.js"></script>
    <!--bootstrap JavaScript file  -->
    <script src="~/js/bootstrap.js"></script>
    <!--Slider JavaScript file  -->
    <script src="~/js/modernizr.custom.63321.js"></script>
    <script src="~/js/jquery.catslider.js"></script>
    <script>
        $(function () {

            $('#mi-slider').catslider();

        });
    </script>
</body>
</html>